### ISSUE TITLE
[FEATURE REQUEST] Upload speed limit / schedule options.

### ISSUE THREAD

**Issue by prefislt** [MaxMaeder/DriveBackupV2#2]
I don't know if this possible but can you add some sort of upload speed limit and/or schedule options to config?
Because right now it's using all servers upload bandwidth, players get kicked and databases disconnects while uploading backup to Google Drive.

**Comment by MaxMaeder** [comment]
Hi!

Actually, the new release DriveBackupV2 1.10 addresses both of these issues. 

You can specify a list of dates and a time you want the server to backup at, similar to the alarm function on your smartphone.

You can also configure the priority of the backup thread. This is relative to the default, so if you do -2, it will be two less than the default.

I submitted the release for review on Bukkit last night, so it could take a few days to get approved. If you don’t want to wait, you can snag it from the releases tab of this GitHub.

Let me know if this fixes your problem,
Max

**Comment by prefislt** [comment]
Great but how threads priority will lower upload speed? Issue right now is that if I uploading pretty big backup files to Google Drive it's using my whole server nodes network capacity and other servers on the same node can have issues because of that.

**Comment by MaxMaeder** [comment]
Approximately how much network bandwidth do you have?

**Comment by prefislt** [comment]
I'm on shared hosting. It have 1 Gbps network bandwidth. 

Plugin uploaded files with like +50 MB/s speed then databases started to timed out, very high ping 
for players and etc. I want limit upload speed to like 10 MB/s so I'm not cause any issues to other users on the same node.

**Comment by MaxMaeder** [comment]
Try setting the thread priority to -4, the minimum. 

Players timing out could be due to the server being overloaded, and not able to respond fast enough to the incoming requests. With a lower thread priority, the server will prioritize responding to the incoming requests over backing up.

1 Gbps is more than enough to handle responding to players and backing up at a fast speed simultaneously, which is why I don't think this is responsible for the issue you are having.

To use the features added in the new version, like this one, you must remove the `config.yml` from your server and restart it, so it can generate a new `config.yml` with the new settings. You can copy your old settings over manually.

**Comment by MaxMaeder** [comment]
Even if you are sharing hardware with other users, your server host should have a virtualization service in place that prevents you from using more than your fair share of bandwidth.

**Comment by MaxMaeder** [comment]
Are you still encountering the same issue, or did the fix work for you?

**Comment by prefislt** [comment]
Upload speed is still pretty high but i have no issues as right now.

**Comment by MaxMaeder** [comment]
Ok, if you experience the issue again let me know and I will look into adding support for limiting the upload speed.
