### ISSUE TITLE
Can not backup world_nether

### ISSUE THREAD

**Issue by SimonKlemp** [MaxMaeder/DriveBackupV2#51]
Hey, I frequently have problems with backuping my files. I backup the world, plugins, nether and the end. It always backups the end first, which works fine. Then, it tries to backup the nether. Sometimes it runs into errors which makes the whole filesystem (/directory) read only. I attached some screenshots with the error. I also cannot send the log itself, because the file system is read only and does not write into the log. The last thing that gets saved in the logs is also attached.
I hope you can help me. I have not yet figured out how to properly reproduce it. Sometimes it works just fine, sometimes not.
![Annotation 2021-06-05 214352](https://user-images.githubusercontent.com/38714960/120903915-4e176380-c649-11eb-81a2-6979ffb794b3.png)
![Annotation 2021-06-05 214341](https://user-images.githubusercontent.com/38714960/120903916-4f489080-c649-11eb-96f3-5ab3123088c4.png)
![Annotation 2021-06-05 214326](https://user-images.githubusercontent.com/38714960/120903918-5079bd80-c649-11eb-93aa-fa82aa0bac61.png)
![Annotation 2021-06-05 220131](https://user-images.githubusercontent.com/38714960/120903959-9a62a380-c649-11eb-805f-8e35e26cb93c.png)

**Comment by rhld16** [comment]
Does this issue still occur? If so what is your server version and plugin version?

**Comment by Cheaterraptor** [comment]
Hey, thanks for the answer. Sorry, I forgot to include that. 
The issue occurs occasionally. It has not happened since I opened the issue, but I also only have played one time. 
My Plugin version is the latest, I think this is 1.4.0. I am currently running on this Spigot version: 
" This server is running CraftBukkit version 3086-Spigot-9fb885e-5912843 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) " (I hope this is what you meant.)

**Comment by oddstr13** [comment]
This issue is way more likely to be due to hardware failure than this plugin.
When the filesystem goes read-only, there should be some information about it in your kernel logs ( `dmesg` ).

Something like a corrupted filesystem or a bad connection to the disk in question could cause this to happen.

Worn out SD card or SSD could also cause this, but then the filesystem is likely to stay read-only for the rest of eternity.
