### ISSUE TITLE
[Request] Allow Google Drive folder IDs to be specified

### ISSUE THREAD

**Issue by Permanently** [MaxMaeder/DriveBackupV2#54]
Or, at least, document how to backup to shared drives.

I'd like to be able to specify what folder/drive to upload to by ID, which would make more sense than typing out the path (at least to me).

**Comment by MaxMaeder** [comment]
So the reason we have you specify the path instead of the folder ID is that due to the Google Drive permissions the plugin requests, the plugin can only create/edit/delete files in folders it creates. Therefore, you can't specify the ID of a folder because that folder would already have to exist.

Similarly, you can't back up to shared drives because of the permissions.

Hope this clears this up!

**Comment by Permanently** [comment]
Can permissions not be elevated?

**Comment by rhld16** [comment]
If we were to elevate permissions we would have to get our app certified by Google and we wouldn't be able to use device code authentication which is extreamly convenient.

**Comment by MaxMaeder** [comment]
We could always have team drive users go through a more involved authentication process, but we still would need to get our app verified and host a simple website to assist with the authentication flow.
